#include "diana_grammar.h"

const AttrTypeInfo attr_type_tbl[191] = {
  {1,"A_ACTUAL","PTABT_ND","PART"},{2,"A_ALIGNM","PTABT_ND","PART"},
  {3,"A_BINARY","PTABT_ND","PART"},{4,"A_BLOCK_","PTABT_ND","PART"},
  {5,"A_CLUSTE","PTABT_ND","PART"},{6,"A_CONNEC","PTABT_ND","PART"},
  {7,"A_CONSTD","PTABT_ND","PART"},{8,"A_CONSTT","PTABT_ND","PART"},
  {9,"A_CONTEX","PTABT_ND","PART"},{10,"A_D_","PTABT_ND","PART"},
  {11,"A_D_CHAR","PTABT_ND","PART"},{12,"A_D_R_","PTABT_ND","PART"},
  {13,"A_D_R_VO","PTABT_ND","PART"},{14,"A_EXCEPT","PTABT_ND","PART"},
  {15,"A_EXP","PTABT_ND","PART"},{16,"A_EXP1","PTABT_ND","PART"},
  {17,"A_EXP2","PTABT_ND","PART"},{18,"A_EXP_VO","PTABT_ND","PART"},
  {19,"A_FORM_D","PTABT_ND","PART"},{20,"A_HAVING","PTABT_ND","PART"},
  {21,"A_HEADER","PTABT_ND","PART"},{22,"A_ID","PTABT_ND","PART"},
  {23,"A_INDICA","PTABT_ND","PART"},{24,"A_ITERAT","PTABT_ND","PART"},
  {25,"A_MEMBER","PTABT_ND","PART"},{26,"A_NAME","PTABT_ND","PART"},
  {27,"A_NAME_V","PTABT_ND","PART"},{28,"A_NOT_NU","PTABT_U2","PART"},
  {29,"A_OBJECT","PTABT_ND","PART"},{30,"A_P_IFC","PTABT_ND","REF"},
  {31,"A_PACKAG","PTABT_ND","PART"},{32,"A_RANGE","PTABT_ND","PART"},
  {33,"A_SPACE","PTABT_ND","PART"},{34,"A_STM","PTABT_ND","PART"},
  {35,"A_SUBPRO","PTABT_ND","PART"},{36,"A_SUBUNI","PTABT_ND","PART"},
  {37,"A_TRANS","PTABT_ND","PART"},{38,"A_TYPE_R","PTABT_ND","PART"},
  {39,"A_TYPE_S","PTABT_ND","PART"},{40,"A_UNIT_B","PTABT_ND","PART"},
  {41,"A_UP","PTABT_ND","REF"},{42,"A_WHERE","PTABT_ND","PART"},
  {43,"AS_ALTER","PTABT_ND","PART"},{44,"AS_APPLY","PTABT_ND","PART"},
  {45,"AS_CHOIC","PTABT_ND","PART"},{46,"AS_COMP_","PTABT_ND","PART"},
  {47,"AS_DECL1","PTABT_ND","PART"},{48,"AS_DECL2","PTABT_ND","PART"},
  {49,"AS_DSCRM","PTABT_ND","PART"},{50,"AS_DSCRT","PTABT_ND","PART"},
  {51,"AS_EXP","PTABT_ND","PART"},{52,"AS_FROM","PTABT_ND","PART"},
  {53,"AS_GROUP","PTABT_ND","PART"},{54,"AS_ID","PTABT_ND","PART"},
  {55,"AS_INTO_","PTABT_ND","PART"},{56,"AS_ITEM","PTABT_ND","PART"},
  {57,"AS_LIST","PTABTSND","PART"},{58,"AS_NAME","PTABT_ND","PART"},
  {59,"AS_ORDER","PTABT_ND","PART"},{60,"AS_P_","PTABT_ND","PART"},
  {61,"AS_P_ASS","PTABT_ND","PART"},{62,"AS_PRAGM","PTABT_ND","PART"},
  {63,"AS_SET_C","PTABT_ND","PART"},{64,"AS_STM","PTABT_ND","PART"},
  {65,"C_ENTRY_","PTABT_U4","REF"},{66,"C_FIXUP","PTABT_LS","REF"},
  {67,"C_FRAME_","PTABT_U4","REF"},{68,"C_LABEL","PTABT_U4","REF"},
  {69,"C_OFFSET","PTABT_U4","REF"},{70,"C_VAR","PTABT_PT","REF"},
  {71,"L_DEFAUL","PTABT_U4","REF"},{72,"L_INDREP","PTABT_TX","REF"},
  {73,"L_NUMREP","PTABT_TX","REF"},{74,"L_Q_HINT","PTABT_TX","REF"},
  {75,"L_SYMREP","PTABT_TX","REF"},{76,"S_ADDRES","PTABT_S4","REF"},
  {77,"S_ADEFN","PTABT_ND","REF"},{78,"S_BASE_T","PTABT_ND","REF"},
  {79,"S_BLOCK","PTABT_ND","REF"},{80,"S_BODY","PTABT_ND","REF"},
  {81,"S_COMP_S","PTABT_ND","REF"},{82,"S_CONSTR","PTABT_ND","REF"},
  {83,"S_DEFN_PRIVATE","PTABT_ND","REF"},{84,"S_DISCRI","PTABT_ND","REF"},
  {85,"S_EXCEPT","PTABT_ND","REF"},{86,"S_EXP_TY","PTABT_ND","REF"},
  {87,"S_FIRST","PTABT_ND","REF"},{88,"S_FRAME","PTABT_ND","REF"},
  {89,"S_IN_OUT","PTABT_U4","REF"},{90,"S_INIT_E","PTABT_ND","REF"},
  {91,"S_INTERF","PTABT_ND","REF"},{92,"S_LAYER","PTABT_S4","REF"},
  {93,"S_LOCATI","PTABT_S4","REF"},{94,"S_NORMARGLIST","PTABT_ND","REF"},
  {95,"S_NOT_NU","PTABT_U2","REF"},{96,"S_OBJ_DE","PTABT_ND","REF"},
  {97,"S_OBJ_TY","PTABT_ND","REF"},{98,"S_OPERAT","PTABT_RA","REF"},
  {99,"S_PACKIN","PTABT_ND","REF"},{100,"S_POS","PTABT_U4","REF"},
  {101,"S_RECORD","PTABT_ND","REF"},{102,"S_REP","PTABT_U4","REF"},
  {103,"S_SCOPE","PTABT_ND","REF"},{104,"S_SIZE","PTABT_ND","REF"},
  {105,"S_SPEC","PTABT_ND","REF"},{106,"S_STM","PTABT_ND","REF"},
  {107,"S_STUB","PTABT_ND","REF"},{108,"S_T_SPEC","PTABT_ND","REF"},
  {109,"S_T_STRU","PTABT_ND","REF"},{110,"S_VALUE","PTABT_U2","REF"},
  {111,"SS_BINDS","PTABTSND","REF"},{112,"SS_BUCKE","PTABT_LS","REF"},
  {113,"SS_EXLST","PTABTSND","REF"},{114,"SS_SQL","PTABTSND","REF"},
  {115,"A_CALL","PTABT_U2","REF"},{116,"A_CHARSET","PTABT_ND","PART"},
  {117,"A_CS","PTABT_ND","PART"},{118,"A_EXT_TY","PTABT_U2","REF"},
  {119,"A_FILE","PTABT_ND","PART"},{120,"A_FLAGS","PTABT_U2","REF"},
  {121,"A_LANG","PTABT_U2","REF"},{122,"A_LIB","PTABT_ND","PART"},
  {123,"A_METH_FLAGS","PTABT_U4","REF"},{124,"A_PARTN","PTABT_ND","PART"},
  {125,"A_REFIN","PTABT_ND","PART"},{126,"A_RTNING","PTABT_ND","PART"},
  {127,"A_STYLE","PTABT_U2","REF"},{128,"A_TFLAG","PTABT_U4","REF"},
  {129,"A_UNUSED","PTABTSND","PART"},{130,"AS_PARMS","PTABT_ND","PART"},
  {131,"L_RESTRICT_REFERENCES","PTABT_U4","REF"},{132,"S_CHARSET_EXPR","PTABT_ND","REF"},
  {133,"S_CHARSET_FORM","PTABT_U2","REF"},{134,"S_CHARSET_VALUE","PTABT_U2","REF"},
  {135,"S_FLAGS","PTABT_U2","REF"},{136,"S_LIB_FLAGS","PTABT_U4","REF"},
  {137,"SS_PRAGM_L","PTABT_ND","REF"},{138,"A_AUTHID","PTABT_TX","REF"},
  {139,"A_BIND","PTABT_ND","PART"},{140,"A_OPAQUE_SIZE","PTABT_ND","PART"},
  {141,"A_OPAQUE_USELIB","PTABT_ND","PART"},{142,"A_SCHEMA","PTABT_TX","REF"},
  {143,"A_STM_STRING","PTABT_ND","PART"},{144,"A_SUPERTYPE","PTABT_ND","PART"},
  {145,"AS_USING_","PTABT_ND","PART"},{146,"S_INTRO_VERSION","PTABT_U4","REF"},
  {147,"A_LIMIT","PTABT_ND","PART"},{148,"A_PERCENT","PTABT_ND","PART"},
  {149,"A_SAMPLE","PTABT_ND","PART"},{150,"A_AGENT","PTABT_ND","REF"},
  {151,"A_AGENT_INDEX","PTABT_U4","REF"},{152,"A_AGENT_NAME","PTABT_ND","PART"},
  {153,"A_ALTERACT","PTABT_U2","REF"},{154,"A_BITFLAGS","PTABT_U4","REF"},
  {155,"A_EXTERNAL","PTABT_ND","PART"},{156,"A_EXTERNAL_CLASS","PTABT_ND","PART"},
  {157,"A_HANDLE","PTABT_PT","REF"},{158,"A_IDENTIFIER","PTABT_ND","PART"},
  {159,"A_KIND","PTABT_U2","REF"},{160,"A_LIBAGENT_NAME","PTABT_ND","REF"},
  {161,"A_NUM_INH_ATTR","PTABT_U2","REF"},{162,"A_ORIGINAL","PTABT_TX","REF"},
  {163,"A_PARALLEL_SPEC","PTABT_ND","REF"},{164,"A_PARTITIONING","PTABT_ND","REF"},
  {165,"A_STREAMING","PTABT_ND","REF"},{166,"A_TYPE_BODY","PTABT_ND","REF"},
  {167,"AS_ALTERS","PTABTSND","REF"},{168,"AS_ALTS","PTABTSND","REF"},
  {169,"AS_ALTTYPS","PTABTSND","REF"},{170,"AS_HIDDEN","PTABTSND","PART"},
  {171,"C_ENTRY_PT","PTABT_U4","REF"},{172,"C_VT_INDEX","PTABT_U2","REF"},
  {173,"L_TYPENAME","PTABT_TX","REF"},{174,"S_CMP_TY","PTABT_ND","REF"},
  {175,"S_CURRENT_OF","PTABT_ND","PART"},{176,"S_DECL","PTABT_ND","REF"},
  {177,"S_LENGTH_SEMANTICS","PTABT_U4","REF"},{178,"S_STMT_FLAGS","PTABT_U4","REF"},
  {179,"S_VTFLAGS","PTABT_U4","REF"},{180,"SS_FUNCTIONS","PTABTSND","REF"},
  {181,"SS_INTO","PTABTSND","PART"},{182,"SS_LOCALS","PTABTSND","PART"},
  {183,"SS_TABLES","PTABT_LS","REF"},{184,"SS_VTABLE","PTABTSND","REF"},
  {185,"A_BEGCOL","PTABT_U4","REF"},{186,"A_BEGLIN","PTABT_U4","REF"},
  {187,"A_ENDCOL","PTABT_U4","REF"},{188,"A_ENDLIN","PTABT_U4","REF"},
  {189,"S_BLKFLG","PTABT_U2","REF"},{190,"S_INDCOL","PTABT_ND","REF"}
};

const AttrVersionEntry attr_vsn_tbl[] = {
  {D_ARRAY,6,9999999},{D_ATTRIB,5,8105000},{D_BLOCK,12,8105000},
  {D_BLOCK,13,9999999},{D_BLOCK,14,9999999},{D_BLOCK,15,9999999},
  {D_BLOCK,16,9999999},{D_CASE,5,9000000},{D_CASE,6,9999999},{D_CASE,7,9999999},
  {D_COMP_U,8,8105000},{D_COMP_U,9,8105000},{D_CONSTR,9,9999999},
  {D_DEF_OP,13,9000000},{D_F_BODY,5,9999999},{D_F_BODY,6,9999999},
  {D_F_BODY,7,9999999},{D_F_BODY,8,9999999},{D_F_DECL,5,9999999},
  {D_F_DECL,6,9999999},{D_IF,4,9999999},{D_IF,5,9999999},
  {D_LOOP,8,9999999},{D_LOOP,9,9999999},{D_P_BODY,4,9999999},
  {D_P_BODY,5,9999999},{D_P_BODY,6,9999999},{D_P_BODY,7,9999999},
  {D_P_DECL,4,9999999},{D_P_DECL,5,9999999},{D_R_,9,8105000},
  {D_R_,10,8105000},{D_R_,11,8105000},{D_R_,12,8105000},
  {D_R_,13,9000000},{D_R_,14,9000000},{D_R_,15,9000000},{D_R_,16,9000000},
  {D_RANGE,4,9000000},{D_RANGE,5,9999999},{D_RANGE,6,9999999},
  {D_S_BODY,5,9999999},{D_S_BODY,6,9999999},{D_S_BODY,7,9999999},
  {D_S_BODY,8,9999999},{D_VAR,5,9000000},{DI_EXCEP,7,8105000},
  {DI_FUNCT,17,8105000},{DI_FUNCT,18,9000000},{DI_FUNCT,19,9000000},
  {DI_FUNCT,20,9000000},{DI_IN,9,9999999},{DI_IN,10,9999999},
  {DI_IN_OU,8,9999999},{DI_OUT,7,8105000},{DI_OUT,8,9999999},
  {DI_PROC,17,8105000},{DI_PROC,18,9000000},{DI_PROC,19,9000000},
  {DI_PROC,20,9000000},{DI_SUBTY,3,8105000},{DI_TYPE,7,8105000},
  {Q_C_BODY,6,9999999},{Q_C_BODY,7,9999999},{Q_FETCH_,5,8106000},
  {Q_TABLE,10,8105000},{Q_TABLE,11,9000000},{QI_CURSO,16,8105000},
  {QI_CURSO,17,9000000},{D_EXTERNAL,10,8105000},{D_EXTERNAL,11,9000000},
  {D_EXTERNAL,12,9000000},{D_EXTERNAL,13,9000000},{D_LIBRARY,4,9000000},
  {D_S_PT,4,9000000},{D_FORALL,3,9000000},{Q_EXEC_IMMEDIATE,4,9000000},
  {Q_EXEC_IMMEDIATE,5,9000000},{D_CASE_EXP,5,9999999},{D_CASE_EXP,6,9999999},
  {0,0,0}
};

// Node attribute lists indexed by node type id
static const int attr_data[][24] = {
  {0},
  {0},{0},{0},{0},
  {AS_LIST,S_EXP_TY,S_CONSTR,S_NORMARGLIST}, // D_AGGREG
  {0},{0},{0},
  {AS_CHOIC,AS_STM,S_SCOPE,C_OFFSET,A_UP}, // D_ALTERN
  {0},
  {A_NAME,AS_APPLY}, // D_APPLY
  {AS_DSCRT,A_CONSTD,S_SIZE,S_PACKIN,A_TFLAG,AS_ALTTYPS}, // D_ARRAY
  {A_NAME,A_EXP,C_OFFSET,A_UP}, // D_ASSIGN
  {A_D_,A_ACTUAL}, // D_ASSOC
  {A_NAME,A_ID,S_EXP_TY,S_VALUE,AS_EXP}, // D_ATTRIB
  {A_EXP1,A_BINARY,A_EXP2,S_EXP_TY,S_VALUE}, // D_BINARY
  {AS_ITEM,AS_STM,AS_ALTER,C_OFFSET,SS_SQL,C_FIXUP,S_BLOCK,S_SCOPE,S_FRAME,A_UP,S_LAYER,S_FLAGS,A_ENDLIN,A_ENDCOL,A_BEGLIN,A_BEGCOL}, // D_BLOCK
  {0},
  {A_NAME,A_EXP,S_EXP_TY,S_VALUE}, // D_C_ATTR
  {A_EXP,AS_ALTER,C_OFFSET,A_UP,S_CMP_TY,A_ENDLIN,A_ENDCOL}, // D_CASE
  {0},
  {A_NAME,A_EXP,A_RANGE}, // D_COMP_R
  {A_CONTEX,A_UNIT_B,AS_PRAGM,SS_SQL,SS_EXLST,SS_BINDS,A_UP,A_AUTHID,A_SCHEMA}, // D_COMP_U
  {AS_LIST,A_UP}, // D_COMPIL
  {A_EXP_VO,AS_STM,S_SCOPE,A_UP}, // D_COND_C
  {0},
  {AS_ID,A_TYPE_S,A_OBJECT,A_UP}, // D_CONSTA
  {A_NAME,A_CONSTT,A_NOT_NU,S_T_STRU,S_BASE_T,S_CONSTR,S_NOT_NU,A_CS,S_FLAGS}, // D_CONSTR
  {AS_LIST}, // D_CONTEX
  {A_NAME,A_EXP,S_EXP_TY,S_VALUE}, // D_CONVER
  {0},{0},
  {AS_ITEM,AS_STM,AS_ALTER,C_OFFSET,SS_SQL,C_FIXUP,S_BLOCK,S_SCOPE,S_FRAME,A_UP}, // D_DECL
  {0},
  {L_SYMREP,S_SPEC,S_BODY,S_LOCATI,S_STUB,S_FIRST,C_OFFSET,C_FIXUP,C_FRAME_,C_ENTRY_,S_LAYER,A_METH_FLAGS,C_ENTRY_PT}, // D_DEF_OP
  {AS_ID,A_NAME}, // D_DEFERR
  {0},
  {A_CONSTD,S_SIZE}, // D_DERIVE
  {A_D_R_VO,AS_P_}, // D_ENTRY
  {A_NAME,AS_P_ASS,S_NORMARGLIST,A_UP}, // D_ENTRY_
  {0},
  {AS_ID,A_EXCEPT,A_UP}, // D_EXCEPT
  {A_NAME_V,A_EXP_VO,S_STM,C_OFFSET,S_BLOCK,A_UP}, // D_EXIT
  {AS_P_,A_NAME_V,S_OPERAT,A_UP}, // D_F_
  {A_ID,A_HEADER,A_BLOCK_,A_UP,A_ENDLIN,A_ENDCOL,A_BEGLIN,A_BEGCOL}, // D_F_BODY
  {A_NAME,AS_P_ASS,S_EXP_TY,S_VALUE,S_NORMARGLIST}, // D_F_CALL
  {A_ID,A_HEADER,A_FORM_D,A_UP,A_ENDLIN,A_ENDCOL}, // D_F_DECL
  {0},{0},{0},{0},
  {AS_DECL1,AS_DECL2,A_UP}, // D_F_SPEC
  {0},{0},
  {A_ID,A_D_R_}, // D_FOR
  {AS_P_,S_OPERAT,A_UP}, // D_FORM
  {A_NAME,AS_P_ASS,S_NORMARGLIST,C_OFFSET,A_UP}, // D_FORM_C
  {0},
  {A_NAME,C_OFFSET,S_BLOCK,S_SCOPE,C_FIXUP,A_UP}, // D_GOTO
  {AS_LIST,C_OFFSET,A_UP,A_ENDLIN,A_ENDCOL}, // D_IF
  {AS_ID,A_NAME,A_EXP_VO,A_INDICA,S_INTERF}, // D_IN
  {0},
  {AS_ID,A_NAME,A_EXP_VO,A_INDICA,S_INTERF}, // D_IN_OUT
  {A_NAME}, // D_INDEX
  {A_NAME,AS_EXP,S_EXP_TY}, // D_INDEXE
  {AS_LIST,A_UP}, // D_INNER_
  {0},
  {A_RANGE,S_SIZE,S_T_STRU,S_BASE_T}, // D_INTEGE
  {S_DISCRI}, // D_L_PRIV
  {AS_ID,A_STM,A_UP}, // D_LABELE
  {A_ITERAT,AS_STM,C_OFFSET,C_FIXUP,S_BLOCK,S_SCOPE,A_UP,A_ENDLIN,A_ENDCOL}, // D_LOOP
  {A_EXP,A_MEMBER,A_TYPE_R}, // D_MEMBER
  {AS_CHOIC,A_EXP}, // D_NAMED
  {A_ID,A_STM,A_UP}, // D_NAMED_
  {0},{0},{0},
  {A_CS}, // D_NULL_A
  {0},
  {C_OFFSET,A_UP}, // D_NULL_S
  {AS_ID,A_EXP}, // D_NUMBER
  {L_NUMREP,S_EXP_TY,S_VALUE}, // D_NUMERI
  {0},{0},
  {AS_ID,A_NAME,A_EXP_VO,A_INDICA,S_INTERF}, // D_OUT
  {AS_P_,S_OPERAT,A_P_IFC,A_UP}, // D_P_
  {A_ID,A_BLOCK_,A_UP,A_ENDLIN,A_ENDCOL,A_BEGLIN,A_BEGCOL}, // D_P_BODY
  {A_NAME,AS_P_ASS,S_NORMARGLIST,C_OFFSET,A_UP}, // D_P_CALL
  {A_ID,A_PACKAG,A_UP,A_ENDLIN,A_ENDCOL}, // D_P_DECL
  {AS_DECL1,AS_DECL2,A_UP}, // D_P_SPEC
  {A_EXP,S_EXP_TY,S_VALUE}, // D_PARENT
  {A_NAME,AS_P_ASS,S_EXP_TY,S_VALUE,S_NORMARGLIST}, // D_PARM_C
  {L_SYMREP,A_NAME,A_NAME_V}, // D_PARM_F
  {A_ID,AS_P_ASS,A_UP}, // D_PRAGMA
  {S_DISCRI}, // D_PRIVAT
  {A_NAME,A_EXP,S_EXP_TY,S_VALUE}, // D_QUALIF
  {AS_LIST,S_SIZE,S_DISCRI,S_PACKIN,S_RECORD,S_LAYER,A_UP,A_TFLAG,A_NAME,A_SUPERTYPE,A_OPAQUE_SIZE,A_OPAQUE_USELIB,A_EXTERNAL_CLASS,A_NUM_INH_ATTR,SS_VTABLE,AS_ALTTYPS}, // D_R_
  {A_NAME,A_ALIGNM,AS_COMP_}, // D_R_REP
  {A_NAME_V,C_OFFSET,A_UP}, // D_RAISE
  {A_EXP1,A_EXP2,S_BASE_T,S_LENGTH_SEMANTICS,S_BLKFLG,S_INDCOL}, // D_RANGE
  {A_NAME,A_UP}, // D_RENAME
  {A_EXP_VO,C_OFFSET,S_BLOCK,A_UP}, // D_RETURN
  {A_ID,A_D_R_}, // D_REVERS
  {0},
  {A_D_,A_HEADER,A_BLOCK_,A_UP,A_ENDLIN,A_ENDCOL,A_BEGLIN,A_BEGCOL}, // D_S_BODY
  {0},
  {A_D_,A_HEADER,A_SUBPRO,A_UP}, // D_S_DECL
  {A_NAME,A_D_CHAR,S_EXP_TY}, // D_S_ED
  {0},
  {A_NAME,A_D_R_,S_EXP_TY,S_CONSTR}, // D_SLICE
  {L_SYMREP,S_EXP_TY,S_CONSTR,S_VALUE,A_CS}, // D_STRING
  {0},
  {A_ID,A_CONSTD,A_UP}, // D_SUBTYP
  {A_NAME,A_SUBUNI,A_UP}, // D_SUBUNI
  {0},{0},{0},{0},{0},{0},{0},
  {A_ID,AS_DSCRM,A_TYPE_S,A_UP}, // D_TYPE
  {0},{0},{0},
  {AS_LIST}, // D_USE
  {L_SYMREP,S_DEFN_PRIVATE,SS_BUCKE,S_OPERAT}, // D_USED_B
  {L_SYMREP,S_DEFN_PRIVATE,S_EXP_TY,S_VALUE}, // D_USED_C
  {L_SYMREP,S_DEFN_PRIVATE,SS_BUCKE}, // D_USED_O
  {0},{0},
  {AS_ID,A_TYPE_S,A_OBJECT,A_UP,A_EXTERNAL}, // D_VAR
  {A_EXP,A_UP}, // D_WHILE
  {AS_LIST}, // D_WITH
  {L_SYMREP}, // DI_ARGUM
  {L_SYMREP}, // DI_ATTR_
  {L_SYMREP,S_OBJ_TY,S_INIT_E,S_COMP_S}, // DI_COMP_
  {L_SYMREP,S_OBJ_TY,S_ADDRES,S_OBJ_DE,C_OFFSET,S_FRAME,S_FIRST}, // DI_CONST
  {L_SYMREP,S_OBJ_TY,S_INIT_E,S_FIRST,S_COMP_S}, // DI_DSCRM
  {0},
  {L_SYMREP,S_OBJ_TY,S_POS,S_REP}, // DI_ENUM
  {L_SYMREP,S_EXCEPT,C_OFFSET,S_OBJ_DE,S_FRAME,S_BLOCK,S_INTRO_VERSION}, // DI_EXCEP
  {L_SYMREP,S_SPEC,S_BODY,S_LOCATI,S_STUB,S_FIRST,C_OFFSET,C_FIXUP,C_FRAME_,C_ENTRY_,S_FRAME,S_LAYER}, // DI_FORM
  {L_SYMREP,S_SPEC,S_BODY,S_LOCATI,S_STUB,S_FIRST,C_OFFSET,C_FIXUP,C_FRAME_,C_ENTRY_,S_FRAME,A_UP,S_LAYER,L_RESTRICT_REFERENCES,A_METH_FLAGS,SS_PRAGM_L,S_INTRO_VERSION,A_PARALLEL_SPEC,C_VT_INDEX,C_ENTRY_PT}, // DI_FUNCT
  {0},
  {L_SYMREP,S_OBJ_TY,S_INIT_E,S_FIRST,C_OFFSET,S_FRAME,S_ADDRES,SS_BINDS,A_UP,A_FLAGS}, // DI_IN
  {L_SYMREP,S_OBJ_TY,S_FIRST,C_OFFSET,S_FRAME,S_ADDRES,A_FLAGS,A_UP}, // DI_IN_OU
  {L_SYMREP,S_OBJ_TY,C_OFFSET,S_FRAME}, // DI_ITERA
  {L_SYMREP,S_T_SPEC}, // DI_L_PRI
  {L_SYMREP,S_STM,C_FIXUP,C_LABEL,S_BLOCK,S_SCOPE,A_UP,S_LAYER}, // DI_LABEL
  {L_SYMREP,S_STM,A_UP,S_LAYER}, // DI_NAMED
  {L_SYMREP,S_OBJ_TY,S_INIT_E}, // DI_NUMBE
  {L_SYMREP,S_OBJ_TY,S_FIRST,C_OFFSET,S_FRAME,S_ADDRES,A_FLAGS,A_UP}, // DI_OUT
  {L_SYMREP,S_SPEC,S_BODY,S_ADDRES,S_STUB,S_FIRST,C_FRAME_,S_LAYER,L_RESTRICT_REFERENCES,SS_PRAGM_L}, // DI_PACKA
  {AS_LIST,L_SYMREP}, // DI_PRAGM
  {L_SYMREP,S_T_SPEC}, // DI_PRIVA
  {L_SYMREP,S_SPEC,S_BODY,S_LOCATI,S_STUB,S_FIRST,C_OFFSET,C_FIXUP,C_FRAME_,C_ENTRY_,S_FRAME,A_UP,S_LAYER,L_RESTRICT_REFERENCES,A_METH_FLAGS,SS_PRAGM_L,S_INTRO_VERSION,A_PARALLEL_SPEC,C_VT_INDEX,C_ENTRY_PT}, // DI_PROC
  {L_SYMREP,S_T_SPEC,S_INTRO_VERSION}, // DI_SUBTY
  {0},
  {L_SYMREP,S_T_SPEC,S_FIRST,S_LAYER,L_RESTRICT_REFERENCES,SS_PRAGM_L,S_INTRO_VERSION}, // DI_TYPE
  {L_SYMREP,S_ADEFN}, // DI_U_ALY
  {L_SYMREP,S_DEFN_PRIVATE,S_OPERAT}, // DI_U_BLT
  {L_SYMREP,S_DEFN_PRIVATE,SS_BUCKE,L_DEFAUL}, // DI_U_NAM
  {L_SYMREP,S_DEFN_PRIVATE,S_EXP_TY,S_VALUE}, // DI_U_OBJ
  {L_SYMREP,S_FIRST}, // DI_USER
  {L_SYMREP,S_OBJ_TY,S_ADDRES,S_OBJ_DE,C_OFFSET,S_FRAME,L_DEFAUL}, // DI_VAR
  {AS_LIST,S_BLOCK,S_SCOPE,A_UP}, // DS_ALTER
  {AS_LIST}, // DS_APPLY
  {AS_LIST}, // DS_CHOIC
  {AS_LIST}, // DS_COMP_
  {AS_LIST}, // DS_D_RAN
  {0}, // DS_D_VAR
  {AS_LIST,A_UP}, // DS_DECL
  {AS_LIST,S_SIZE}, // DS_ENUM_
  {AS_LIST}, // DS_EXP
  {0},{0},{0},
  {AS_LIST}, // DS_ID
  {AS_LIST,A_UP}, // DS_ITEM
  {AS_LIST}, // DS_NAME
  {AS_LIST}, // DS_P_ASS
  {AS_LIST}, // DS_PARAM
  {AS_LIST,A_UP}, // DS_PRAGM
  {A_UP}, // DS_SELEC
  {AS_LIST,A_UP}, // DS_STM
  {AS_LIST,A_UP}, // DS_UPDNW
  {A_NAME,A_NAME_V}, // Q_ALIAS_
  {A_UP}, // Q_AT_STM
  {A_EXP1,L_DEFAUL,A_EXP2}, // Q_BINARY
  {L_SYMREP,L_INDREP,S_EXP_TY,S_VALUE,S_IN_OUT,C_OFFSET,S_DEFN_PRIVATE}, // Q_BIND
  {A_D_,A_HEADER,A_BLOCK_,C_OFFSET,A_UP,A_ENDLIN,A_ENDCOL}, // Q_C_BODY
  {A_NAME,AS_P_ASS,S_EXP_TY,S_VALUE,S_NORMARGLIST,A_UP}, // Q_C_CALL
  {A_D_,A_HEADER,A_UP}, // Q_C_DECL
  {A_RANGE}, // Q_CHAR
  {A_NAME,A_UP}, // Q_CLOSE_
  {0},
  {A_TRANS,A_UP}, // Q_COMMIT
  {A_NAME}, // Q_COMMNT
  {A_EXP1,A_EXP2,A_UP}, // Q_CONNEC
  {A_NAME,A_EXP}, // Q_CREATE
  {A_NAME}, // Q_CURREN
  {AS_P_,A_NAME_V,S_OPERAT,A_UP}, // Q_CURSOR
  {A_ID,A_PACKAG,A_UP}, // Q_DATABA
  {0},{0},{0},
  {A_NAME,A_EXP_VO,L_Q_HINT,A_UP,A_RTNING}, // Q_DELETE
  {A_NAME}, // Q_DICTIO
  {A_NAME}, // Q_DROP_S
  {L_DEFAUL,AS_EXP,A_EXP,L_Q_HINT}, // Q_EXP
  {0},
  {A_NAME,L_DEFAUL,A_EXP_VO,S_EXP_TY}, // Q_F_CALL
  {A_NAME,A_ID,A_UP,S_FLAGS,A_LIMIT}, // Q_FETCH_
  {0},
  {AS_LIST}, // Q_FRCTRN
  {L_DEFAUL,A_UP}, // Q_GENSQL
  {A_NAME,AS_NAME,A_EXP,A_UP,S_FLAGS,A_REFIN,L_Q_HINT,A_RTNING}, // Q_INSERT
  {0},
  {A_NAME,A_ID}, // Q_LINK
  {AS_LIST,L_DEFAUL}, // Q_LOCK_T
  {0},
  {A_RANGE}, // Q_NUMBER
  {A_NAME,AS_P_ASS,S_NORMARGLIST,A_UP}, // Q_OPEN_S
  {L_DEFAUL,A_EXP}, // Q_ORDER_
  {A_TRANS,A_UP}, // Q_RLLBCK
  {A_ID}, // Q_ROLLBA
  {0},
  {0},
  {A_ID}, // Q_SAVEPO
  {A_ID,A_PACKAG,A_UP}, // Q_SCHEMA
  {A_EXP,AS_INTO_,AS_ORDER,S_OBJ_TY,AS_NAME,S_FLAGS}, // Q_SELECT
  {A_EXP,S_LAYER,A_EXP2}, // Q_SEQUE
  {A_NAME,A_EXP}, // Q_SET_CL
  {0},
  {A_NAME_V,A_STM,C_OFFSET,C_VAR,A_UP}, // Q_SQL_ST
  {A_UP}, // Q_STATEM
  {A_EXP,S_EXP_TY,A_FLAGS,AS_ORDER}, // Q_SUBQUE
  {A_EXP,S_LAYER,L_DEFAUL}, // Q_SYNON
  {AS_LIST,A_SPACE,A_EXP,A_CLUSTE,A_EXP2,C_OFFSET,S_LAYER,A_UP,A_TYPE_S,A_TFLAG,AS_HIDDEN}, // Q_TABLE
  {AS_FROM,A_WHERE,A_CONNEC,AS_GROUP,A_HAVING,S_BLOCK,S_LAYER}, // Q_TBL_EX
  {A_NAME,AS_SET_C,A_EXP_VO,L_Q_HINT,A_UP,A_RTNING}, // Q_UPDATE
  {0},{0},
  {AS_LIST,A_EXP,L_DEFAUL,S_LAYER,A_UP}, // Q_VIEW
  {L_SYMREP,L_INDREP,S_EXP_TY,S_VALUE,S_IN_OUT,C_OFFSET,A_FLAGS}, // QI_BIND_
  {L_SYMREP,S_SPEC,S_BODY,S_LOCATI,S_STUB,S_FIRST,C_OFFSET,C_FIXUP,C_FRAME_,C_ENTRY_,S_FRAME,S_LAYER,A_UP,L_RESTRICT_REFERENCES,SS_PRAGM_L,S_INTRO_VERSION,C_ENTRY_PT}, // QI_CURSO
  {L_SYMREP,S_SPEC,S_BODY,S_ADDRES,S_STUB,S_FIRST,C_OFFSET,C_FRAME_,S_LAYER}, // QI_DATAB
  {L_SYMREP,S_SPEC,S_BODY,S_ADDRES,S_STUB,S_FIRST,C_OFFSET,C_FRAME_,S_LAYER}, // QI_SCHEM
  {L_SYMREP}, // QI_TABLE
  {0},
  {AS_LIST}, // QS_SET_C
  {L_SYMREP,S_SPEC,S_BODY,S_ADDRES,S_STUB,S_FIRST,C_FRAME_,S_LAYER,A_UP}, // D_ADT_BODY
  {AS_LIST,S_SIZE,S_DISCRI,S_PACKIN,S_RECORD,S_LAYER,A_UP,A_TFLAG}, // D_ADT_SPEC
  {A_CHARSET,S_CHARSET_FORM,S_CHARSET_VALUE,S_CHARSET_EXPR}, // D_CHARSET_SPEC
  {L_SYMREP,S_VALUE,A_UP}, // D_EXT_TYPE
  {A_NAME,A_LIB,AS_PARMS,A_STYLE,A_LANG,A_CALL,A_FLAGS,A_UP,A_UNUSED,AS_P_ASS,A_AGENT,A_AGENT_INDEX,A_LIBAGENT_NAME}, // D_EXTERNAL
  {A_NAME,A_FILE,S_LIB_FLAGS,A_AGENT_NAME}, // D_LIBRARY
  {A_NAME,A_PARTN,S_EXP_TY,A_FLAGS}, // D_S_PT
  {A_TYPE_S,A_UP}, // D_T_PTR
  {A_TYPE_S,A_UP}, // D_T_REF
  {A_FLAGS,A_EXT_TY}, // D_X_CODE
  {A_FLAGS,A_EXT_TY}, // D_X_CTX
  {L_SYMREP,S_DEFN_PRIVATE,A_FLAGS,A_EXT_TY}, // D_X_FRML
  {A_FLAGS,A_EXT_TY}, // D_X_NAME
  {A_FLAGS,A_EXT_TY}, // D_X_RETN
  {A_FLAGS,A_EXT_TY}, // D_X_STAT
  {L_SYMREP,S_SPEC}, // DI_LIBRARY
  {AS_LIST}, // DS_X_PARM
  {0},{0},{0},{0},{0},
  {AS_EXP,S_FLAGS,AS_INTO_}, // Q_RTNING
  {A_ID,A_D_R_,S_FLAGS}, // D_FORALL
  {A_EXP}, // D_IN_BIND
  {A_NAME}, // D_IN_OUT_BIND
  {A_NAME}, // D_OUT_BIND
  {A_D_,A_HEADER,A_SUBPRO,A_UP,A_BIND}, // D_S_OPER
  {A_FLAGS,A_EXT_TY,A_NAME}, // D_X_NAMED_RESULT
  {A_FLAGS,A_EXT_TY,A_NAME,L_SYMREP,S_DEFN_PRIVATE}, // D_X_NAMED_TYPE
  {L_SYMREP,S_OBJ_TY,C_OFFSET,S_FRAME}, // DI_BULK_ITER
  {L_SYMREP,S_SPEC,S_BODY,S_ADDRES,S_STUB,S_FIRST,C_FRAME_,S_LAYER}, // DI_OPSP
  {AS_LIST}, // DS_USING_BIND
  {A_NAME,S_EXP_TY}, // Q_BULK
  {A_NAME,A_STM_STRING,AS_USING_}, // Q_DOPEN_STM
  {A_STM,C_OFFSET,L_RESTRICT_REFERENCES,A_UP}, // Q_DSQL_ST
  {A_STM_STRING,A_ID,AS_USING_,A_RTNING,S_FLAGS}, // Q_EXEC_IMMEDIATE
  {A_PERCENT,A_FLAGS}, // D_PERCENT
  {A_NAME,A_SAMPLE}, // D_SAMPLE
  {AS_ALTERS,A_ALTERACT}, // D_ALT_TYPE
  {AS_CHOIC,A_EXP}, // D_ALTERN_EXP
  {AS_ALTS}, // D_AN_ALTER
  {A_EXP,AS_LIST,S_EXP_TY,S_CMP_TY,A_ENDLIN,A_ENDCOL}, // D_CASE_EXP
  {AS_EXP,S_EXP_TY}, // D_COALESCE
  {A_BITFLAGS,A_IDENTIFIER,AS_EXP,A_UP}, // D_ELAB
  {A_NAME,A_UP}, // D_IMPL_BODY
  {A_EXP1,A_EXP2,S_CMP_TY}, // D_NULLIF
  {A_EXP,S_BLOCK,C_OFFSET,A_UP}, // D_PIPE
  {A_HANDLE,A_ORIGINAL,A_KIND,S_CURRENT_OF,SS_LOCALS,SS_INTO,S_STMT_FLAGS,SS_FUNCTIONS,SS_TABLES,S_OBJ_TY,C_OFFSET,A_UP}, // D_SQL_STMT
  {A_BITFLAGS,A_PARTITIONING,A_STREAMING,A_TYPE_BODY,A_UP}, // D_SUBPROG_PROP
  {S_DECL,L_TYPENAME,S_VTFLAGS,C_ENTRY_}, // VTABLE_ENTRY
  {L_SYMREP}, // D_ELLIPSIS
  {A_ID,AS_EXP} // D_VALIST
};

static const int attr_data_counts[] = {
  0,0,0,0,0,4,0,0,0,5,0,2,6,4,2,5,5,16,0,4,7,0,3,9,2,4,0,4,9,1,4,0,0,10,0,13,2,0,2,2,4,0,3,6,4,8,5,6,0,0,0,0,3,0,0,2,3,5,0,6,5,5,0,5,1,3,2,0,4,1,3,9,3,2,3,0,0,0,1,0,2,2,3,0,0,5,4,7,5,6,3,0,5,2,5,3,2,4,0,8,0,2,3,6,2,4,2,2,4,2,0,3,3,0,0,0,0,0,0,0,4,0,0,0,1,4,4,3,0,0,5,2,1,1,4,7,5,0,4,7,12,20,0,10,8,4,2,8,4,3,8,10,2,2,1,1,8,8,3,4,4,4,3,4,20,3,3,6,2,4,2,5,7,4,4,4,4,0,3,3,3,0,0,0,2,3,3,2,2,2,3,3,2,3,3,3,1,1,3,7,2,2,3,3,3,1,3,3,5,3,3,3,2,2,0,7,3,2,2,5,6,5,2,2,0,0,2,7,8,8,1,0,2,8,8,4,13,4,2,2,2,4,2,2,2,2,2,1,0,0,0,0,0,0,3,3,1,1,1,5,5,4,2,6,9,4,4,4,2,2,4,2,2,2,2,2,12,5,4,2,3,4,2
};

const int* get_node_attr_list(int node_type, int& count) {
  if (node_type < 0 || node_type >= 303) { count = 0; return nullptr; }
  count = attr_data_counts[node_type];
  return attr_data[node_type];
}
