#include "embedded.h"

const char* EMBEDDED_LICENSE =
  "PL/SQL Unwrap v3.0\n"
  "Copyright (C) 2026  Manuel FLURY\n\n"
  "C++ port of the PL/SQL Unwrapper project by Cameron Marshall\n"
  "https://github.com/oddz/PL-SQL-Unwrapper\n\n"
  "This program is free software: you can redistribute it and/or modify\n"
  "it under the terms of the GNU General Public License as published by\n"
  "the Free Software Foundation, either version 3 of the License, or\n"
  "(at your option) any later version.\n\n"
  "This program is distributed in the hope that it will be useful,\n"
  "but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
  "MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
  "GNU General Public License for more details.\n\n"
  "You should have received a copy of the GNU General Public License\n"
  "along with this program.  If not, see <https://www.gnu.org/licenses/>.\n";

const char* EMBEDDED_README =
  "PL/SQL Unwrap v3.0\n"
  "==================\n\n"
  "Standalone binary to unwrap (and wrap) Oracle PL/SQL source code.\n\n"
  "Original PL/SQL project : https://github.com/oddz/PL-SQL-Unwrapper\n"
  "Original author          : Cameron Marshall\n"
  "C++ port                 : Manuel FLURY\n"
  "License                  : GNU General Public License v3.0\n\n"
  "Supports:\n"
  "  V1 unwrap  — Oracle 8/8i/9i (ported but UNTESTED)\n"
  "  V2 unwrap  — Oracle 10g+ through 23ai\n"
  "  V2 wrap    — encode plain PL/SQL into wrapped format\n"
  "  Obfuscate  — rename identifiers to short names, AES-encrypted restore\n\n"
  "Usage:\n"
  "  unwrap [options] [-i <file>] [-o <file>]\n"
  "  wrap   [options]  -i <file> [-o <file>]\n\n"
  "Options:\n"
  "  -i, --input <file>    input file (stdin if piped)\n"
  "  -o, --output <file>   output file (stdout if omitted)\n"
  "  --v1                  force V1 unwrapper (UNTESTED)\n"
  "  --v2                  force V2 unwrapper\n"
  "  --wrap                wrap source (V2 method)\n"
  "  --keep-comments       preserve comments (default: strip them)\n"
  "  --obfuscate, --obf    rename identifiers to short names\n"
  "  --deobfuscate, --deobf  restore original names (needs passphrase)\n"
  "  -p, --passphrase <key>  encryption passphrase\n"
  "  -l, --license             show license information\n"
  "  -h, --help                show this help\n\n"
  "Oracle-compatible syntax (wrap mode):\n"
  "  iname=<file>  oname=<file>  keep_comments=yes  help=yes\n\n"
  "Limits:\n"
  "  Maximum input file size: 128 MB\n"
  "  V1 unwrapper is ported but lacks real-world validation.\n\n"
  "Build:\n"
  "  Requires cmake, zlib, OpenSSL (C++17).\n"
  "  Debian/Ubuntu: apt install build-essential cmake libz-dev libssl-dev\n"
  "  Fedora/RHEL:   dnf install gcc-c++ cmake zlib-devel openssl-devel\n"
  "  Alpine:        apk add build-base cmake zlib-dev openssl-dev\n"
  "  make\n"
  "  make test\n"
  "  make clean\n\n"
  "When invoked without arguments and stdin is a terminal,\n"
  "usage is displayed instead of reading from stdin.\n";
